# Generated by Django 4.0 on 2021-12-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
