# Generated by Django 4.0 on 2021-12-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car_rating',
        ),
    ]
